### ISSUE TITLE
Write a Contract for Each Sponsor Tier

### ISSUE THREAD

**Issue by href** [SwissPy/sps17#22]
We need to write a contract for each sponsor tier. Do we have anyone that knows how to write good legalese? We can also collaborate here, so if anyone wants to give it a shot, just comment below.

**Comment by dbrgn** [comment]
No experience with that, sorry :)

**Comment by href** [comment]
Well things we have to mention, imho:
- All perks promised to each tier
- What happens if we have to cancel the conference for some reason
- When the contract comes into effect (after payment is made)
- Some disclaimer about how this is a volunteer effort and that we are not responsible for any negative kind of news surrounding the event (say if we trigger a shit-storm for whatever reason).

**Comment by chiesax** [comment]
... adapted from http://www.acmpglobal.org/mpage/2013SPONSFORM

This agreement is between the Swiss Python Summit Association and XXXX. This agreement provides the terms and conditions for sponsors of the Swiss Python Summit 2017, February 17, 2017 Rapperswil, Switzerland.

Description of benefits and sponsor obligations

Sponsor payment. Sponsors agree to pay the full sponsorship fee within 30 days of signing this agreement. Sponsorship fees are non‐refundable with the exception of unforeseen circumstances that force a cancellation of the entire event.

Sponsor personnel. Please keep in mind that all sponsor attendees are representing the sponsor. Therefore, professional dress is suggested.

Intellectual property. Any conference content, including but not limited to photos, videos, slides, or papers, are considered property of the Swiss Python Summit Association and shall not be posted or disseminated by Sponsor without express written approval of the Swiss Python Summit Association .

Indemnification.Both Swiss Python Summit Association and Sponsor (the "Indemnifying Party”) shall indemnify the other party (the "Indemnified Party”) against and save each other harmless from any and all suits, proceedings at law or in equity, claims, liabilities, damages, costs, payments and expenses, including reasonable attorney's fees, asserted against or incurred by the Indemnified Party, arising out of or in connection with the negligence or willful misconduct of the Indemnifying Party in the performance of this Agreement including, but not limited to, any claim for damages to property or injuries to persons, to the extent that such damages or injuries shall have been caused by, or shall have resulted from the willful or negligent acts or omissions of the Indemnifying Party, or its employees or agents.

Complete agreement. This Agreement contains the entire understanding between the parties with respect to the conference sponsorship benefits and obligations and supersedes all prior oral and written understandings, arrangements and agreements between the parties.

**Comment by chiesax** [comment]
... added here: https://github.com/SwissPy/sps17/tree/master/contracts

**Comment by href** [comment]
Awesome, thanks @chiesax ! @dbrgn Can you push your LaTeX templates for the letter, contract and bill? Then I can send out the contracts.

**Comment by dbrgn** [comment]
Will do tonight, when I'm back home!

**Comment by jakeret** [comment]
Impressive ;-), well done

**Comment by chiesax** [comment]
we should probably add some more details about the logo...
- the logo of Platinum Sponsor is placed on a large size format on all promotional materials, included but not limited to the internet site of the conference, lanyards, the printed version of the conference program, posters, video recordings of the conference, ...

also we may say for the aperitif dinner: we will write, on the conference program, that the after party is sponsored by XXX. The logo of XXX will be printed on a poster at the aperitif dinner.

Just suggestions...

**Comment by href** [comment]
Actually I think it's better to let this be vague. If it's specific it only makes it harder for us.
Also, promotional materials does not include everything, lanyards or t-shirts are not promotional in my opinion.

**Comment by href** [comment]
I drafted the contracts/invoices for 4Teamwork and Seantis:
https://github.com/SwissPy/sps17/tree/master/contracts

I took the intellectual property and completeness bits out. I think it goes a bit too much into legalese. As important as language is in a contract, at the end of the day it's the intention that counts and that is clear with/without those paragraphs.

As non-lawyers we can get away with a poorly worded contract if our intention is clear. Adding clauses like this carries the risk of adding legal meaning where we didn't intend any.
